#- platform: cast

- platform: kodi
  host: 192.168.2.71

- platform: spotify
  client_id: !secret spotify-client_id
  client_secret: !secret spotify-client_secret
  
  
- platform: samsungtv
  host: 192.168.2.51
  port: 8001
