- platform: yr
  name: Weather
  forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - pressure

- platform: mqtt
  state_topic: "home-assistant/temprature/outside/balcony"
  name: "Outside Balcony"
  unit_of_measurement: "°C"
  qos: 1

- platform: mqtt
  state_topic: "home-assistant/temprature/inside/livingroom"
  name: "Inside Livingroom"
  unit_of_measurement: "°C"
  qos: 1
  
- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: qnap
  host: !secret qnap-host
  username: !secret qnap-username
  password: !secret qnap-password
  monitored_conditions:
#    - drive_temp
#    - drive_smart_status
    - status
    - system_temp
    - cpu_temp
    - cpu_usage
    - memory_percent_used
#    - volume_percentage_used

#- platform: template
#  sensors:
#    low_battery:
#      friendly_name: "Low Battery"
#      value_template: >
#        {%- set threshold = 40 -%}
#        {%- set domains = ['light', 'switch', 'sensor', 'zwave', 'lock'] -%}
#        {%- for domain in domains -%}
#        {%- for item in states[domain] if ((item.attributes.battery_level is defined and item.attributes['battery_level'] | int < threshold) or ("battery" in item.name | lower and ((item.state | int < threshold and item.state|int != 0) or item.state | lower == "low" or item.state | lower == "unknown"))) -%}
#            {{ item.attributes.friendly_name }}{%- if not loop.last %}, {% endif -%}
#        {%- endfor -%}
#        {%- endfor -%}