title: My Awesome Home
# Include external resources
resources:
  - url: /ui-lovelace/my-custom-card.js
    type: js
  - url: /ui-lovelace/my-webfont.css
    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/local/background.jpg") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views: !include_dir_list ui-lovelace/views/
